### ISSUE TITLE
Implementation or forecasts for Naïve2 model

### ISSUE THREAD

**Issue by ankile** [carlanetto/Mcomp2018#2]
Hello!

We're using the M4 dataset for some research as part of our master's thesis. We have come across a problem when trying to calculate the OWA, though. The Naïve2 model that is supposed to be used as the denominator in the weighted average is relatively poorly defined.

I was wondering whether anyone knows if there is an existing implementation out there that is correct or if there exists recalculated forecasts or sMAPE/MASE losses for them?

This would be incredibly helpful in our thesis, thank you!

**Comment by vangspiliot** [comment]
Hi!

The forecasts of the benchmarks (and the participants) are available at the M4 repository

https://github.com/Mcompetitions/M4-methods/tree/master/Point%20Forecasts

Hope that helps

**Comment by ankile** [comment]
Yes, that helps! I must've overseen this somehow... Thank you!
